config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#welcome'
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations',
          passwords: 'users/passwords'
  }

  resources :cities
  resources :airports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airline.rb
class Airline < ApplicationRecord
  has_many :flights, class_mame: "Flight"
  has_many :planes, class_name: "Plane"
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city, class_name: "City", foreign_key: "city_id"
  has_many :flights_by_origin , class_name: "Flight", foreign_key: "origin_airport_id"
  has_many :flights_by_destination, class_name: "Flight", foreign_key: "destination_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :sale_orders, class_name: "SaleOrder"
end

app/models/city.rb
class City < ApplicationRecord
  has_many :airports, class_name: "Airport"
  validates :name, :country_name, :time_zone, presence: true 
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: "Airport", foreign_key: "origin_airport_id"
  belongs_to :destination, class_name: "Airport", foreign_key: "destination_airport_id"
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"
  has_many :itineraries, class_name: "FlightItinerary"
  has_many :planes, through: :itineraries
end

app/models/flight_itinerary.rb
class FlightItinerary < ApplicationRecord
  belongs_to :plane, class_name: "Plane", foreign_key: "plane_id"
  belongs_to :flight, class_name: "Flight", foreign_key: "flight_id"
  has_many :tickets, class_name: "Ticket"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :tickets, class_name: "Ticket"
end

app/models/plane.rb
class Plane < ApplicationRecord
  has_many :itineraries, class_name: "FlightItinerary"
  has_many :flights , through: :itineraries
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
  belongs_to :buyer, class_name: "Buyer", foreign_key: "buyer_id"
  has_many :tickets, class_name: "Ticket"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  #itinerary_id integer
  belongs_to :itinerary, class_name: "FlightItinerary", foreign_key: "itinerary_id"
  belongs_to :sale_order, class_name: "SaleOrder", foreign_key: "sale_order_id"
  belongs_to :passenger, class_name: "Passenger", foreign_key: "passenger_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController

  def index
    @airports = Airport.all
  end

  def new
    @cities = City.all
    @airport = Airport.new
  end

  def create
    @airport = Airport.new(airport_params)
    if @airport.save
      redirect_to airports_path
    else
      render 'new'
    end
  end

  def edit
    @cities = City.all
    @airport = Airport.find_by(id: params[:id])
  end

  def update
    @airport = Airport.find_by(id: params[:id])
    if @airport.update_attributes(airport_params)
      redirect_to airports_path
    else
      render 'edit'
    end
  end

  def destroy
    airport = Airport.find_by(id: params[:id])
    if airport.destroy
      flash[:success] = "Airport Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to airports_path

  end

  private

  #strong parameters
  def airport_params
    params.require(:airport).permit(:name, :city_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to cities_path
    else
      render 'new'
    end
  end

  def edit
    @city = City.find_by(id: params[:id])
  end

  def update
    @city = City.find_by(id: params[:id])
    if @city.update_attributes(city_params)
      redirect_to cities_path
    else
      render 'edit'
    end
  end

  def destroy
    city = City.find_by(id: params[:id])
    if city.destroy
      flash[:success] = "City Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to cities_path

  end

  private

  #strong parameters
  def city_params
    params.require(:city).permit(:name, :country_name, :time_zone)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/airports/edit.html.erb
<div class="container">
<h1 class="text-center">  Edit Airport </h1>
<%= form_for @airport do |f| %>
  <% if @airport.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@airport.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @airport.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:city_id) do %>
        <% @cities.each do |c| -%>
        <%= content_tag(:option, c.name, value: c.id) %>
      <% end %>
    <% end %>
  </div>
  <%= f.submit "Edit Airport", class: "btn btn-primary" %>
  <a href="<%= airports_path %>" class="btn btn-default"> View all </a>
<% end %>
</div>

app/views/airports/index.html.erb
<div class="container">
  <h1 class="text-center"> Airports </h1>
  <section class="row text-center">
      <a href="<%= new_airport_path %>" class="btn btn-default"> New Airport </a>
  </section>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">Airport name</th>
        <th class="text-center">City name</th>
        <th class="text-center">Country name</th>
        <th class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @airports.each do |a| %>
        <tr>
          <td class="text-center"><%= a.name %></td>
          <td class="text-center"><%= a.city.name %></td>
          <td class="text-center"><%= a.city.country_name %></td>
          <td class="text-center">
            <a href="<%= edit_airport_path(a.id) %>" class="btn btn-circle btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="<%= airport_path(a.id) %>" data-method="delete" class="btn btn-circle btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
          </td>
        </tr>
      <% end if @airports.any? %>
    </tbody>
  </table>

</div>

app/views/airports/new.html.erb
<div class="container">
<h1 class="text-center">  New Airport </h1>
<%= form_for @airport do |f| %>
  <% if @airport.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@airport.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @airport.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:city_id) do %>
    <select name="airport [city_id]">
      <% @cities.each do |c| -%>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
    <% end %>
    </select>
  </div>
  <%= f.submit "Create Airport", class: "btn btn-primary" %>
  <a href="<%= airports_path %>" class="btn btn-default"> View all </a>
<% end %>
</div>

app/views/cities/edit.html.erb
<div class="container">
<h1 class="text-center">  Edit City </h1>
<%= form_for @city do |f| %>
  <% if @city.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@city.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @city.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country_name%>
    <%= f.text_field :country_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_zone%>
    <%= f.text_field :time_zone, class: "form-control" %>
  </div>
  <%= f.submit "Edit City", class: "btn btn-primary" %>
  <a href="<%= cities_path %>" class="btn btn-default"> View all </a>
<% end %>
</div>

app/views/cities/index.html.erb
<div class="container">
  <h1 class="text-center"> Cities </h1>
  <section class="row text-center cities-controls">
      <a href="<%= new_city_path %>" class="btn btn-default"> New City </a>
  </section>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">City name</th>
        <th class="text-center">Country name</th>
        <th class="text-center">Tim zone</th>
        <th class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @cities.each do |c| %>
        <tr>
          <td class="text-center"><%= c.name %></td>
          <td class="text-center"><%= c.country_name %></td>
          <td class="text-center"><%= c.time_zone %></td>
          <td class="text-center">
            <a href="<%= edit_city_path(c.id) %>" class="btn btn-circle btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
            <a href="<%= city_path(c.id) %>" data-method="delete" class="btn btn-circle btn-danger"><span class="glyphicon glyphicon-remove"></span></a>
          </td>
        </tr>
      <% end if @cities.any? %>
    </tbody>
  </table>

</div>

app/views/cities/new.html.erb
<div class="container">
<h1 class="text-center">  New City </h1>
<%= form_for @city do |f| %>
  <% if @city.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@city.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @city.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country_name%>
    <%= f.text_field :country_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_zone%>
    <%= f.text_field :time_zone, class: "form-control" %>
  </div>
  <%= f.submit "Create City", class: "btn btn-primary" %>
  <a href="<%= cities_path %>" class="btn btn-default"> View all </a>
<% end %>
</div>